# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Courtney G Ives
email: cgives@me.com
description: Courtney Ives, web & software developer based in Minnesota.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://courtney.ives.mn" # the base hostname & protocol for your site
twitter_username: courtneygives
github_username:  courtneygives

# Build settings
markdown: kramdown
